import Head from "next/head";
import Navbar from "../../components/Navbar";
import AssetsBody from "../../components/AssetsBody";
import Menu from "../../components/Menu";
import { useRouter } from "next/router";
import { useEffect } from "react";

function Assets() {
  const router = useRouter();

  useEffect(() => {
    console.log(router.query.address);
  });

  

 
  return (
    <div className={`font-montserrat relative`}>
      <Head>
        <title>NFTropolis | Assets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <AssetsBody />
      <Menu />
    </div>
  );
}

export default Assets;
