import Head from "next/head";
import Navbar from "../components/Navbar";
import CreateBody from "../components/CreateBody";
import Menu from "../components/Menu";
import ImageEditModal from "../components/ImageEditModal";
import { useSelector } from "react-redux";
import toast, { Toaster } from 'react-hot-toast';

function Create() {

  const editState = useSelector((state: any)=> {return state.imageEditorPopupState})

  return (
    <div className={`font-montserrat relative`}>
      <Head>
        <title>NFTropolis | Create</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <CreateBody />
      {editState && <ImageEditModal/>}
      <Menu/>
      <Toaster
       position="bottom-right"
       reverseOrder={false}
       gutter={8}
      />
    </div>
  );
}

export default Create;
