import Head from "next/head";
import Navbar from "../components/Navbar";
import CreateBody from "../components/CreateBody";
import Menu from "../components/Menu";

function Create() {
  return (
    <div className={`font-montserrat relative`}>
      <Head>
        <title>NFTropolis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <CreateBody />
      <Menu/>
    </div>
  );
}

export default Create;
