import type { NextPage } from "next";
import { ethers } from "ethers";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { nfTropolisAddress } from "../src/nfTropolisAddress";
import nfTropolisABI from "../artifacts/contracts/NFTropolis.sol/NFTropolis.json";
import { marketplaceAddress } from "../src/marketplaceAddress";
import marketplaceABI from "../artifacts/contracts/Marketplace.sol/Marketplace.json";
// import { minterAddress } from '../src/minterAddress'
import metadata from "../data/data.json";
import { saveNFTData } from "../components/reducers/action";
import { client } from "../sanity/sanity.config";
import Menu from "../components/Menu";
import {
  usePrepareContractWrite,
  useContractWrite,
  useContractRead,
  useAccount,
} from "wagmi";
import getCount from "../components/hooks/useCount";
import MarketplaceBody from "../components/MarketplaceBody";
import toast, { Toaster } from 'react-hot-toast';
import Checkout from "../components/Checkout";
import ListBody from "../components/ListBody";


const ListPage = () => {



  return (
    <div className={`font-montserrat relative`}>
      <Head>
        <title>NFTropolis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <ListBody/>
      <Menu />
      <Toaster
      position="bottom-right"
      reverseOrder={false}
      gutter={8}
      />
    </div>
  );
};

export default ListPage;

